import { Startup } from "@/types";

export const STARTUP_DATA: Startup[] = [
  {
    id: "apex-ai",
    name: "Apex AI",
    logoText: "AA",
    logoBg: "linear-gradient(135deg, #10b981, #059669)",
    tagline: "Autonomous multi-agent workflows for enterprise operations.",
    description: "Apex AI orchestrates autonomous software agents that integrate with existing company tools, automating complex tasks like data retrieval, analysis, and report generation with minimal human oversight.",
    sector: "ai-ml",
    sectorLabel: "AI / ML",
    stage: "Seed",
    ask: 1500000,
    founder: "Sarah Jenkins",
    email: "sarah@apexai.io",
    linkedin: "https://www.linkedin.com/in/sarah-jenkins-apex",
    submittedDate: "2026-06-16",
    status: "New",
    location: "Bengaluru, India"
  },
  {
    id: "wealthstream",
    name: "WealthStream",
    logoText: "WS",
    logoBg: "linear-gradient(135deg, #3b82f6, #2563eb)",
    tagline: "Micro-investing and financial wellness for gig-economy workers.",
    description: "WealthStream integrates directly with gig-platforms to automatically round up earnings into diversified portfolios, offering tailored retirement and insurance options for contract workers.",
    sector: "fintech",
    sectorLabel: "Fintech",
    stage: "Pre-seed",
    ask: 500000,
    founder: "David Chen",
    email: "d.chen@wealthstream.com",
    linkedin: "https://www.linkedin.com/in/david-chen-wealthstream",
    submittedDate: "2026-06-14",
    status: "Under Review",
    location: "Mumbai, India"
  },
  {
    id: "bioscribe",
    name: "BioScribe",
    logoText: "BS",
    logoBg: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    tagline: "AI medical scribe translating patient-doctor dialogue into notes.",
    description: "BioScribe uses clinical-grade voice recognition to transcribe patient consultations, auto-generate EHR-compliant reports, and reduce doctor administrative workloads by 70%.",
    sector: "healthtech",
    sectorLabel: "Healthtech",
    stage: "Series A",
    ask: 4000000,
    founder: "Dr. Amanda Ross",
    email: "amanda@bioscribe.health",
    linkedin: "https://www.linkedin.com/in/amanda-ross-bioscribe",
    submittedDate: "2026-06-10",
    status: "Shortlisted",
    location: "Hyderabad, India"
  },
  {
    id: "solarloop",
    name: "SolarLoop",
    logoText: "SL",
    logoBg: "linear-gradient(135deg, #f59e0b, #d97706)",
    tagline: "Decentralized community solar grid optimization software.",
    description: "SolarLoop enables peer-to-peer clean energy sharing by automating micro-transactions between local solar producers and energy consumers using smart grid algorithms.",
    sector: "climate",
    sectorLabel: "Climate Tech",
    stage: "Series B+",
    ask: 12000000,
    founder: "Marcus Vance",
    email: "marcus@solarloop.net",
    linkedin: "https://www.linkedin.com/in/marcus-vance-solarloop",
    submittedDate: "2026-06-17",
    status: "New",
    location: "Delhi, India"
  },
  {
    id: "learnsphere",
    name: "LearnSphere",
    logoText: "LS",
    logoBg: "linear-gradient(135deg, #ec4899, #db2777)",
    tagline: "Adaptive gamified math curriculums for primary schools.",
    description: "LearnSphere's diagnostic engine customizes educational pathways in real time, leveraging gaming dynamics to double student math comprehension and retention rates.",
    sector: "edtech",
    sectorLabel: "Edtech",
    stage: "Seed",
    ask: 800000,
    founder: "Elena Rostova",
    email: "elena@learnsphere.org",
    linkedin: "https://www.linkedin.com/in/elena-rostova-learnsphere",
    submittedDate: "2026-06-08",
    status: "Under Review",
    location: "Pune, India"
  },
  {
    id: "neurocare",
    name: "NeuroCare",
    logoText: "NC",
    logoBg: "linear-gradient(135deg, #14b8a6, #0d9488)",
    tagline: "Non-invasive neuro-stimulation headband for sleep optimization.",
    description: "NeuroCare combines sleep-tracking sensors with low-frequency neural pulses to increase deep sleep duration, helping busy professionals recover faster with fewer hours of sleep.",
    sector: "healthtech",
    sectorLabel: "Healthtech",
    stage: "Seed",
    ask: 1250000,
    founder: "Kenji Takahashi",
    email: "kenji@neurocare.io",
    linkedin: "https://www.linkedin.com/in/kenji-takahashi-neurocare",
    submittedDate: "2026-06-15",
    status: "New",
    location: "Chennai, India"
  },
  {
    id: "paychain",
    name: "PayChain",
    logoText: "PC",
    logoBg: "linear-gradient(135deg, #06b6d4, #0891b2)",
    tagline: "Instant global settlement API for cross-border e-commerce.",
    description: "PayChain aggregates local payment methods and blockchain settlements to offer instant, friction-free transactions for international merchants at 90% lower fees.",
    sector: "fintech",
    sectorLabel: "Fintech",
    stage: "Series A",
    ask: 3500000,
    founder: "Sofia Moreno",
    email: "s.moreno@paychain.dev",
    linkedin: "https://www.linkedin.com/in/sofia-moreno-paychain",
    submittedDate: "2026-06-01",
    status: "Under Review",
    location: "Bengaluru, India"
  },
  {
    id: "ecopack",
    name: "EcoPack Labs",
    logoText: "EP",
    logoBg: "linear-gradient(135deg, #84cc16, #65a30d)",
    tagline: "Water-soluble seaweed packaging replacing single-use plastics.",
    description: "EcoPack Labs manufactures zero-waste, marine-safe packaging materials for food and cosmetics brands that dissolve naturally in water within minutes.",
    sector: "climate",
    sectorLabel: "Climate Tech",
    stage: "Pre-seed",
    ask: 450000,
    founder: "Liam O'Connor",
    email: "liam@ecopacklabs.co",
    linkedin: "https://www.linkedin.com/in/liam-oconnor-ecopack",
    submittedDate: "2026-06-12",
    status: "Shortlisted",
    location: "Kochi, India"
  },
  {
    id: "promptcraft",
    name: "PromptCraft",
    logoText: "PC",
    logoBg: "linear-gradient(135deg, #6366f1, #4f46e5)",
    tagline: "Enterprise prompt engineering registry and testing suite.",
    description: "PromptCraft helps development teams version control, benchmark, and secure prompts for LLM applications, reducing API costs and model output regressions.",
    sector: "ai-ml",
    sectorLabel: "AI / ML",
    stage: "Seed",
    ask: 750000,
    founder: "Michael Chang",
    email: "michael@promptcraft.ai",
    linkedin: "https://www.linkedin.com/in/michael-chang-promptcraft",
    submittedDate: "2026-06-18",
    status: "New",
    location: "San Francisco, US"
  },
  {
    id: "saasify",
    name: "SaaSify",
    logoText: "SF",
    logoBg: "linear-gradient(135deg, #f43f5e, #e11d48)",
    tagline: "No-code customer portal creator for legacy enterprise software.",
    description: "SaaSify hooks into old databases and mainframe APIs to output sleek, customer-facing web and mobile applications in a drag-and-drop builder.",
    sector: "saas",
    sectorLabel: "SaaS",
    stage: "Series A",
    ask: 2800000,
    founder: "Emma Watson",
    email: "emma@saasify.io",
    linkedin: "https://www.linkedin.com/in/emma-watson-saasify",
    submittedDate: "2026-05-28",
    status: "Under Review",
    location: "London, UK"
  }
];

export const SECTORS = [
  { value: "fintech", label: "Fintech" },
  { value: "healthtech", label: "Healthtech" },
  { value: "climate", label: "Climate Tech" },
  { value: "edtech", label: "Edtech" },
  { value: "ai-ml", label: "AI / ML" },
  { value: "saas", label: "SaaS" }
];
